import './style.css'

import './js/icons'
import './js/flight-search'
import './js/swipers'
import './js/budget-range'
import './js/dropdowns'
import './js/hero'
import './js/mobile-sidebar'
import './js/mobile-search'
import './js/navigation'
